### PR TITLE
Update/bulk option delete

### PR DESCRIPTION
**Pull request by ramyakrishnai**
## Proposed changes
Removing the delete option permanently from the bulk options to restrict the users from deleting the brand plugins using bulk options.

JIRA: [https://jira.newfold.com/browse/PRESS0-1416](https://jira.newfold.com/browse/PRESS0-1416?focusedCommentId=14645855#comment-14645855)

Screenshot 2024-06-20 at 7 51 24 PM

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wpscholar** [comment]
@ramyakrishnai - We don't want to prevent a user's ability to bulk delete other plugins, just our plugin.

**Comment by ramyakrishnai** [comment]
Hi @wpscholar , @chrisdavidmiles mentioned that we should remove the delete option from bulk options same as in bh-cloud.

**Comment by chrisdavidmiles** [comment]
@wpscholar this seems to be the lightest touch way to do this. It's also how WP Cloud solves this problem:
IMG_0372

We can [filter plugin action links](https://developer.wordpress.org/reference/hooks/plugin_action_links_plugin_file/) to remove delete for an individual plugin but it doesn't  do anything for the bulk action. And for plugins managed by the host I've seen three ways bulk option is accounted for.

(1) Remove the delete bulk option like in the screenshot. This is what A8C does for atomic and a few others. This is what me and Mike recommend.

(2) Make the plugin an mu which we don't recommend because it would change the deactivation behavior and we're only trying to change the delete behavior.

(3) Keep the delete bulk option in place but make it ineffective on the brand plugin with an admin notice that says something like it can't be deleted. This is possible but seems very ugly and annoying. I'd much rather take the UI option away than present the option and have to explain in copy "sorry Dave, I can't let you do that" 🔴

Perhaps there's another way to do this, and I'm open to suggestions but Mike and I liked option one because removing the option seemed follow the principle of of least astonishment the most. (And we're doing it already in "BH" Cloud since that's how A8C handles it on that platform)

I realize this also means users can't bulk delete other plugins but they can delete them with the inline delete button in action links.

Let us know if you have any other suggestions, otherwise this is my recommendation on how to move forward.

**Comment by wpscholar** [comment]
@chrisdavidmiles I was thinking maybe some JS that would hide and disable the plugin's checkbox if the user selects "Delete" from the bulk options dropdown. Sure, it might be a little odd, but taking away a user's ability to troubleshoot other issues by disabling the most common tool for doing so might not go over well either.

**Comment by wpscholar** [comment]
@chrisdavidmiles  However, I didn't realize that A8C did that, and I am not finding anyone complaining about it when doing a few web searches, which is surprising.  As such, maybe removing it isn't as big of a deal as I think it would be.

**Review by wpscholar — APPROVED** [review]
@ramyakrishnai I've confirmed that this is the path we are taking with Chris. Thanks!

**Pull request merged**
